### PR TITLE
#296 apk download on login screen

### PR DESCRIPTION
**Pull request by n00on**
I added the launchUrl package to launch the download url for the .apk.  
I found this to be the best method.  

Also the docker compose now also builds the apk.  
The docker compose dev does not to save time and resources.

My first approach was adding something to the `index.html` but this wouldn't have been a good solution and you would see the link the whole time 
```html
  <a href="/assets/assets/app-release.apk" download style="z-index: 10000;position: absolute">
    APK
  </a>
```

### CODE REVIEW

**Comment by lukas0820** [comment]
I noticed that you are trying to adjust the Java version of the android build action. I've already done it here: https://github.com/MANVSim/MANVSim/pull/297/commits/bb8b028a0cefc6c2e7232bf12da41c2c851a4f9b

**Comment by lukas0820** [comment]
At the moment, we are discarding the artifact from the Android build workflow in the GitHub action, but we could store it and offer it for download via GitHub instead. We could then link to it directly in the app, which would save us from having to build it through Docker Compose. Alternatively, we could consider creating a separate Dockerfile for this. Can we discuss this on Monday?

**Comment by n00on** [comment]
image

**Comment by n00on** [comment]
The apk install works on my phone with just a few warnings if I really trust this app :) @lukas0820

**Review by lukas0820 — APPROVED** [review]

**Pull request merged**
