### PR TITLE
bug(app) #271: stop unnecessary builds

### LINKED ISSUE #271: App: Unnecessary Duplicate Build on PRs
The Github Actions are executed twice for each platform during a pull request

### PR DESCRIPTION
**Pull request by lukas0820**
closes #271

### CODE REVIEW

**Comment by n00on** [comment]
My suggestion is using pull_request as it mostly makes sense for checks when you have a pull request ready?  
And then on every push to main like:

```yml
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'app/**'
```

What do you think?

**Review by n00on — COMMENTED** [review]
See comment above @lukas0820

**Comment by lukas0820** [comment]
> What do you think? @lukas0820

@n00on I like having regular builds on feature branches even without a pull request. They help me identify commits where the build fails on platforms that I don't regularly build the app on, so I would prefer to keep them

I think regular main build are a good idea, maybe we can do something like:

```
on:
  push:
    branches:
      - main
  push:
    branches-ignore:
      - main
    paths:
      - 'app/**'
```

**Comment by n00on** [comment]
@lukas0820 good points, consider this solution approved!

**Pull request merged**
